ieg.upload<-function(comi,treat,prefix,category=NA)
{
  comi=comi[,colSums(comi)>0]
  sp.name=colnames(comi)
  samp.name=rownames(comi)
  treat=treat[match(samp.name,rownames(treat)),]
  if(is.na(category))
  {
    category=sp.name
  }
  comi[comi==0]=""
  comm=data.frame(cate=category,t(comi))
  write.table(data.frame(GeneID=rownames(comm),comm),file=paste("output/",prefix,".ieg.comm.txt",sep=""),quote=FALSE,sep="\t",row.names=FALSE)
  treatment=list()
  for(j in 1:ncol(treat))
  {
    tr.lev=levels(as.factor(treat[,j]))
    treatment[[j]]=data.frame(treatm=matrix(,nrow=length(tr.lev),ncol=1))  
    for(i in 1:length(tr.lev))
    {
      samp=paste(rownames(treat)[treat[,j]==tr.lev[i]],collapse=",")
      treatment[[j]][i,1]=paste("T",tr.lev[i],":",samp,sep="")
    }
    write.table(treatment[[j]],file=paste("output/",prefix,".ieg.treat",j,".txt",sep=""),quote=FALSE,row.names=FALSE,col.names=FALSE)
  }
  names(treatment)=colnames(treat)
  output=list(com=comm,treatment=treatment)
  output
}